### DISCUSSION TITLE
Nested yaml structures

### DISCUSSION THREAD

**Discussion by binwiederhier** [urfave/cli#1781] [Q&A] [answered]
Howdy,

Thanks for urfave/cli! I've been using it for years in many projects. Great job!

I'd like to know if it is possible to represent something like this with the lib:

```
converters:
  - grafana:
      title: object.key
      message: object.nested.nested.key
  - github:
      title: object.key
      message: object.nested.nested.key
```

I tried fiddling with the `Generic` flag, without success. I'd be okay if this is only available via the yaml alt  source.

Btw, do you have a Discord/chat where one could ask these questions? I couldn't find one.
