### DISCUSSION TITLE
Get Flag type and required status

### DISCUSSION THREAD

**Discussion by xoxys** [urfave/cli#1845] [Q&A] [answered]
Is there a way to find out the type of flag and if the flag is required? I would like to use this information to generate documentation.

**Comment by dearchap** [comment]
Have you looked at the App.ToMan() and App.ToMarkdown() functions to generate docs ?

**Reply by xoxys** [reply]
Yes, but I need a different format, so I build my own implementation similar to `ToMarkdown`. Nevertheless, as far as I can see the information if a flag is `required` and the flag type (`stringFlag`, `boolFlag`, etc.) is also not available while using `ToMarkdown`.

**Reply by dearchap** [reply]
Can you give me an example of what your docs output would look for different flags ?

**Reply by xoxys** [reply]
Sure.

```go
[]cli.Flag{
        &cli.BoolFlag{
	        Name:        "become",
	        Usage:       "enable privilege escalation",
	        EnvVars:     []string{"PLUGIN_BECOME"},
	        Destination: &settings.Become,
	        Category:    category,
        },
        &cli.StringFlag{
	        Name:        "become-method",
	        Usage:       "privilege escalation method to use",
	        EnvVars:     []string{"PLUGIN_BECOME_METHOD", "ANSIBLE_BECOME_METHOD"},
	        Destination: &settings.BecomeMethod,
	        Category:    category,
        },
        &cli.StringFlag{
	        Name:        "become-user",
	        Usage:       "privilege escalation user to use",
	        EnvVars:     []string{"PLUGIN_BECOME_USER", "ANSIBLE_BECOME_USER"},
	        Destination: &settings.BecomeUser,
	        Category:    category,
        },
}
```

It is translated into this YAML file. The name is parsed from `flag.GetEnvVars()[0]`, see https://github.com/thegeeklab/wp-plugin-go/blob/main/docs/docs.go#L75-L100

```YAML
---
properties:
  - name: become
    description: |
      enable privilege escalation
    defaultvalue: false

  - name: become_method
    description: |
      privilege escalation method to use

  - name: become_user
    description: |
      privilege escalation user to use
```

What I would like to have is:

```YAML
---
properties:
  - name: become
    description: |
      enable privilege escalation
    defaultvalue: false
    required: false
    type: BoolFlag
```
