### ISSUE TITLE
q: Loading only subtree of a config

### ISSUE THREAD

**Issue by danmx** [urfave/cli#1180]
## Question

Is there a way to load only selected subtree of a config file (selected config "profile")?

## Example

With a config file like this:

```toml
[default]
  type = "slow"
  colour = "green"
[private]
  type = "fast"
  colour = "yellow"
```

I'd like to be able to add in a root flags `--config-profile=private` and get values/flags from `private` subtree of the config.
