### ISSUE TITLE
change the location of args and options.

### ISSUE THREAD

**Issue by xbsummer** [urfave/cli#1431]
## Checklist

* [x] Are you running the latest v2 release? The list of releases is [here](https://github.com/urfave/cli/releases).
* [x] Did you check the manual for your release? The v2 manual is [here](https://github.com/urfave/cli/blob/main/docs/v2/manual.md).
* [x] Did you perform a search about this feature? Here's the [Github guide](https://help.github.com/en/github/managing-your-work-on-github/using-search-to-filter-issues-and-pull-requests) about searching.

## What problem does this solve?

Another way of writing on the command line

## Solution description
```
     old:   command [options ...] [arguments...]
 another:   command [arguments...] [options ...] 

example:
     old:   command test -d name=123 -d age=18 -d sex=MALE arg1 arg2 arg3 ....
 another:   command test  arg1 -arg2 arg3 ....  -d name=123  age=18 sex=MALE  #-arg2 not an option
```
from the example, you can see:
  the old way, each option can only be followed by one value, if there are multiple values, must be multiple `-d` options, If there is no `-d` option，multiple values may lead to inability to distinguish args.
  the another way, an option can be followed by multiple values, multiple values are separated by spaces, if the args are preceded by -, you can verify whether it is an option, until the first option is found, the front is all args

recommended to add a switch, which uses the old parsing mode by default, and use the new parsing mode  if the switch is turned on。

## Describe alternatives you've considered

A clear and concise description of any alternative solutions or
features you've considered.
